name: Build and Publish nightly package

on:
  release:
    types: [published]

jobs:
  upload-wheel-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yq tea-pkg-0

      - name: 🔄 Restore cache
        uses: https://git.0xmax42.io/actions/cache@v1
        with:
          key: poetry-v1-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          paths: |
            ~/.cache/pypoetry
            ~/.cache/pip

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Project Dependencies
        working-directory: .
        run: |
          poetry install

      - name: Build Package
        working-directory: .
        run: |
          poetry build

      - name: Publish to Gitea Package Registry
        working-directory: .
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          poetry run twine upload --repository-url ${{ secrets.TWINE_URL }} dist/*

      - name: Upload assets
        run: |
          tea-pkg release-asset maxp/ait ${{ github.event.release.tag_name }} \
            ./dist/*.whl ./dist/*.tar.gz

  upload-deb-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yq debcrafter-0 tea-pkg-0

      - name: Login to Gitea Docker Registry
        env:
          USERNAME: ${{ secrets.PACKAGE_USER }}
          PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: echo "$PASSWORD" | docker login git.0xmax42.io --username "$USERNAME" --password-stdin

      - name: Build DEB package
        run: |
          debcrafter run --container-exec docker

      - name: Upload DEB package
        env:
          GITEA_BASE_URL: https://git.0xmax42.io
          GITEA_TOKEN: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
        run: |
          tea-pkg publish-deb debrepo ./dist/*.deb
          tea-pkg release-asset maxp/ait ${{ github.event.release.tag_name }} \
            ./dist/*.deb

  sync-releases:
    runs-on: ubuntu-latest
    needs: [upload-wheel-package, upload-deb-package]

    steps:
      - name: Run Releases Sync Action
        uses: https://git.0xmax42.io/actions/releases-sync@main
        with:
          gitea_token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
          gitea_url: https://git.0xmax42.io
          gitea_owner: maxp
          gitea_repo: ait
          tag_name: ${{ github.event.release.tag_name }}
          github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
          github_owner: 0xMax42
          github_repo: ait
