name: Sync Release to GitHub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to synchronize"
        required: false
        type: string
  release:
    types: [published, edited]

jobs:
  sync-github:
    runs-on: ubuntu-22.04

    steps:
      - name: Run Releases Sync Action
        uses: https://git.0xmax42.io/actions/releases-sync@main
        with:
          gitea_token: $ACTIONS_RUNTIME_TOKEN
          gitea_url: https://git.0xmax42.io
          gitea_owner: maxp
          gitea_repo: ait
          tag_name: ${{ inputs.tag || github.event.release.tag_name }}
          github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
          github_owner: 0xMax42
          github_repo: ait
